name: Test
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Golang 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.23.8
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Golang 1.14.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.8
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make build
